config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def show
    set_task
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    raise unless task.save

    redirect_to task_path(task)
  end

  def edit
    set_task
  end

  def update
    set_task
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    set_task
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f|%>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.text_field :completed %>
  </div>
  <%= f.submit %>
<% end %>
</form>

app/views/tasks/edit.html.erb
<h1>Update a Task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
<% @tasks.each do |task| %>
  <li><%= task.title %> - <%= task.details %> - <%= task.completed %></li> <%=link_to "See details", task_path(id: task.id) %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<p><%= @task.id %></p>

<%=link_to "Back to tasks", tasks_path %>
<%=link_to "Edit", edit_task_path(@task) %>
<%=link_to "Destroy", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>